### ISSUE TITLE
CHOICE type

### ISSUE THREAD

**Issue by barbodar** [sop/asn1#1]
Hi,
Thanks for your nice job,
why this library has no CHOICE type ?

**Comment by sop** [comment]
Hi!

That's because CHOICE is an abstract type, that can't be determined from DER data by the parser.
This library doesn't currently support ASN.1 template parsing, which would solve the problem. At the moment you have to programmatically handle such cases.

Please see for example [X.509 GeneralName](https://github.com/sop/x509/blob/0.3.0/lib/X509/GeneralName/GeneralName.php#L67) parsing for the use case of CHOICE handling.
