### ISSUE TITLE
Function usage invokeArgs() (@call_with_passing_by_reference) is deprecated.

### ISSUE THREAD

**Issue by danielmarschall** [sop/asn1#11]
Hello,

I was checking the files on my server with [PHP codefixer](https://github.com/wapmorgan/PhpCodeFixer) and I found following error in ElementDecodeTest.php [line 72](https://github.com/sop/asn1/blob/master/test/tests/ElementDecodeTest.php#L72):

> Function usage invokeArgs() (@call_with_passing_by_reference) is deprecated.

**Comment by sop** [comment]
Hi!

I ran phpcf and it indeed reports an error as you described. However, i would argue that this is a bug in PhpCodeFixer, since that's the only way to pass refs to reflected methods. See [PHP docs](https://www.php.net/manual/en/reflectionmethod.invokeargs.php#refsect1-reflectionmethod.invokeargs-notes) for info.

**Comment by sop** [comment]
I reported this and the author fixed it.
wapmorgan/PhpCodeFixer#38
