### ISSUE TITLE
Best way to get oid from base64 encoded public key

### ISSUE THREAD

**Issue by maxisme** [sop/asn1#2]
I am currently checking whether a string is a public key by doing this:

```
$key = base64_decode("MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyl6XUhrx0v4zKaVpQ53GLYrKy6BR6s5gtSLorJ9FbwSVP+wIsMut2q3LaYpWeJuC1BIZ3isNsRqmkdlP4qaLYeCQOMr5VMJkzsjL/lkxt4jvxSCB8U0ms+dxgjFOWAzE1IA/HYwyVs1ge4FeXGcJ3lcYyZ2IFOJ+jXNee2tgzR8rdNWsV7Px9QutKm9YYkJ+xuBQ++Q4HdKTRgU7Xoq8n1lfgzAXSsHFIxdWbUJqK7WPUcY3kfX364N+0fKmmZysNlj6ZegK/295h+EQwJTTjVipIhWFR7xQ37mDv8sp/rxEyO51cLt0AUwdyReqOhkfzJMFCBufTQqnwBDP6CJ5JHfeXeIW/T3lYsmnYJiKwhJqe58mA5GG0zG5+fUfqPeSX7BzJN4kqF69/gQJlmJIGjxRy+9mW7rQJ7YD8pgqW3k+KUppcACiTuIldKgaUEvMhNNIj2GyAYk+ggTh6ULRaKAAPdTBonLWnEIUSzL3f6DuFgiaCeySKkeS7ARP2HQdKsIphUav8bScYxsfLw6+EAeSGklPWHbsJ4sdJWVrRzLWNIa04Xm0IzT8xZRVfoJoi09+yYY2GD62F1YWki7wTOhHSdOuZ9hSDRHkAHEjkReJp0o9SmbSROo9wYJ8wwOP2Fwx900XATvx702k2/YizvdR7Ytz9sA2zpVFXVgeLvMCAwEAAQ==");
$seq = Sequence::fromDER($key);
$oid = $seq->at(0)->at(0)->asObjectIdentifier()->oid();
```

and if `$oid` equals `1.2.840.113549.1.1.1` then it is an RSA public key.

I am a bit sceptical about the  `->at(0)->at(0)->` and can this change? How would you recommend getting the `oid`?

**Comment by maxisme** [comment]
Shortened to `$seq->at(0)->at(0)->oid()`

**Comment by sop** [comment]
Looks like you're decoding a public key am i right? More specifically a SubjectPublicKeyInfo structure, which is a sequence of AlgorithmIdentifier and a BitString. AlgorithmIdentifier is further a sequence of OID and parameters.

You're correctly traversing `$seq->at(0)->at(0)->asObjectIdentifier()->oid();`. The structure should never change, since it's standardized by in RFC's (notably in [rfc5280](https://tools.ietf.org/html/rfc5280#section-4.1)).

I've actually already implemented public key parsing in [crypto-types](https://github.com/sop/crypto-types) package, if that's what you're after. Getting an RSA public key from your data is as easy as `PublicKeyInfo::fromDER($key)->publicKey();`. Parsing is implemented [here](https://github.com/sop/crypto-types/blob/master/lib/CryptoTypes/Asymmetric/PublicKeyInfo.php#L50).

**Comment by maxisme** [comment]
Ahh brilliant. Thank you for your fast reply!
